# frozen_string_literal: true
source "https://rubygems.org"
gem "activerecord"
gem "rake"
gem "sinatra-activerecord"
gem "sqlite3", "~>1.4.2"
gem "pry"
gem "require_all"
gem "tty-prompt", "~>0.22.0"
gem "byebug"
